export const countries = [
  {
    id: "1",
    name: "United States",
    flag: "https://flagcdn.com/w320/us.png",
    checked: false,
  },
  {
    id: "2",
    name: "Canada",
    flag: "https://flagcdn.com/w320/ca.png",
    checked: false,
  },
  {
    id: "3",
    name: "Cuba",
    flag: "https://flagcdn.com/w320/cu.png",
    checked: false,
  },
  {
    id: "4",
    name: "Jamaica",
    flag: "https://flagcdn.com/w320/jm.png",
    checked: false,
  },
  {
    id: "5",
    name: "Puerto Rico",
    flag: "https://flagcdn.com/w320/pr.png",
    checked: false,
  },
  {
    id: "6",
    name: "Dominican Republic",
    flag: "https://flagcdn.com/w320/do.png",
    checked: false,
  },
  {
    id: "7",
    name: "Bahamas",
    flag: "https://flagcdn.com/w320/bs.png",
    checked: false,
  },
  {
    id: "8",
    name: "Honduras",
    flag: "https://flagcdn.com/w320/hn.png",
    checked: false,
  },
  {
    id: "9",
    name: "Guatemala",
    flag: "https://flagcdn.com/w320/gt.png",
    checked: false,
  },
  {
    id: "10",
    name: "El Salvador",
    flag: "https://flagcdn.com/w320/sv.png",
    checked: false,
  },
  {
    id: "11",
    name: "Costa Rica",
    flag: "https://flagcdn.com/w320/cr.png",
    checked: false,
  },
  {
    id: "12",
    name: "Trinidad and Tobago",
    flag: "https://flagcdn.com/w320/tt.png",
    checked: false,
  },
  {
    id: "13",
    name: "Panama",
    flag: "https://flagcdn.com/w320/pa.png",
    checked: false,
  },
];
